language: en

pipeline:
  # First, translate non-English messages to English
  - name: components.google_translate.GoogleTranslateComponent
    base_language: en
    supported_languages:
      - en
      - es
      - fr
      
  # Then process with standard NLU pipeline
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    epochs: 50
  - name: RulePolicy
