version: "3.9"

services:
  rasa:
    image: rasa/rasa:3.7.0
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./actions:/app/actions
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./data:/app/data
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./nlu.yml:/app/nlu.yml
      - ./stories.yml:/app/stories.yml
      - ./rules.yml:/app/rules.yml
      - ./components:/app/components   # your Google Translate component
    command: ["run", "--enable-api", "--cors", "*"]
    depends_on:
      - action_server

  action_server:
    image: rasa/rasa-sdk:3.7.0
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: ["start", "--actions", "actions"]

  # Optional: Postgres tracker store for conversation history
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
      POSTGRES_DB: rasa
    ports:
      - "5432:5432"

