version: "3.9"

services:
  rasa:
    image: rasa/rasa:3.7.0
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./actions:/app/actions
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./data:/app/data
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./components:/app/components   # your Google Translate component
    command: ["run", "--enable-api", "--cors", "*"]
    depends_on:
      - action_server
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=rasa
      - DB_PASSWORD=rasa
      - DB_DB=rasa
    networks:
      - rasa-network

  action_server:
    image: rasa/rasa-sdk:3.7.0
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: ["start", "--actions", "actions"]
    networks:
      - rasa-network

  # Postgres tracker store for conversation history
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
      POSTGRES_DB: rasa
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge

volumes:
  postgres-data:
