FROM rasa/rasa-sdk:3.7.0

# Copy actions directory
COPY actions /app/actions

# Install additional dependencies
RUN pip install requests googletrans==4.0.0-rc1

# Set working directory
WORKDIR /app

# Start the action server
CMD ["start", "--actions", "actions"]
